### ISSUE TITLE
AUR packages

### ISSUE THREAD

**Issue by Confetti-Camouflage** [nwg-piotr/nwg-shell#1]
Would you be willing to create AUR packages for your projects?

**Comment by nwg-piotr** [comment]
You mean the part written in Go, right? The rest is available in AUR.

If it comes to golang and the gotk3 library: it's going to be difficult, for at least 2 reasons:

- downloading and building the library itself for the first time takes ages;
- gotk3 frequently happens to be unable to build with the latest Go version. Users would need to downgrade Go first.

IMO the only solution would be to package binaries. Do you think it would be acceptable?

**Comment by nwg-piotr** [comment]
done
