### ISSUE TITLE
Will this work fine with Wayfire?

### ISSUE THREAD

**Issue by Freemason-12** [nwg-piotr/nwg-shell#11]
I know that this is for Sway, but I'm still curious since at least from README it looks cool))

**Comment by nwg-piotr** [comment]
Not all the stuff will work on Wayfire.

- nwg-panel doesn't have a taskbar capable of working on WF;
- nwg-dock won't work at all;
- nwg-displays won't work, until I add some more code to it (doable);
- of course autotiling won't work as well.

To summarize: you can use most of the components, but not the shell itself.

**Comment by Freemason-12** [comment]
Will there be a work done in order to make these things compatible with WF, or you will focus on Sway only?

**Comment by nwg-piotr** [comment]
https://github.com/nwg-piotr/nwg-shell#support-for-other-wms
