### ISSUE TITLE
Custom directory for "screenshot"

### ISSUE THREAD

**Issue by phtalo** [nwg-piotr/nwg-shell#128]
First of all, thanks for all of this amazing work. Your project has been a great way to enhance sway in all possible directions.

I noticed that in the script `screenshot` the directory for saving the screenshot has been hardcoded. I think it would be nice to be able to set the directory with a flag e.g. `screenshot -d $HOME/custom-dir _mode_`, as my only option is to do a manual edit to the script which will be then overwritten as updates come. Another option would be to be able to set this variable via the nwg-shell-config utility, but that is of course more complex.

Thanks again.

**Comment by nwg-piotr** [comment]
>  I can't manage to delete the issue though.

It will last forever, in case anyone wanted to ask the same question. :)
