### ISSUE TITLE
[package request] Gentoo

### ISSUE THREAD

**Issue by anoraktrend** [nwg-piotr/nwg-shell#132]
drop some ebuilds in guru?

**Comment by nwg-piotr** [comment]
I haven't put my hand on Gentoo ever in my life, sorry. I only do packaging for Arch User Repository. I'll gladly help, if necessary.

**Comment by Schievel1** [comment]
I do the packaging into Gentoo right now. I submitted some nwg-packages to the GURU already, so stay tuned for them to pop up soon

**Comment by nwg-piotr** [comment]
@anoraktrend 

@Schievel1 Thanks! You packaged nwg-shell itself, what a nice surprise! Maybe you could also write a Gentoo version of the [installer script](https://github.com/nwg-piotr/nwg-shell/blob/main/install/arch.sh), and add some docs for people who have never used Gentoo, like myself?

**Comment by Schievel1** [comment]
I have to say thanks. With all my humble little projects I can only imagine what a massive effort you put into this. 

Tbf I am not that keen on installer scripts, especially when it comes to gentoo. 
Portage should handle all that, and people can choose themselves what they want or don't want from the optional packages by just installing those packages via portage. 

I will write a page in the gentoo wiki, though.

**Comment by nwg-piotr** [comment]
Probably good Wiki will be enough for Gentoo users. Feel free to add a link in the nwg-shell Wiki. It's open for public edition.
