### ISSUE TITLE
[testing] Obarun Linux

### ISSUE THREAD

**Issue by anoraktrend** [nwg-piotr/nwg-shell#139]
Obarun is a unique Linux Distro that uses s6 and 66 as it's init system. It's an overlay derivative of Arch Linux, (uses the arch repos and it's own), I may need to write a SystemD-less variant of swayidle or something because it can't be installed on Obarun. This is seemingly the only blocker, but it may be just one of many. Every other dependency that it tried to install did install. Feel free to close this issue if you do not care to support yet another distro that'd be more work.

**Comment by nwg-piotr** [comment]
Come to think of it, gtklock could be an optional dependency. We still have swaylock. I'd only need to make nwg-shell-config ready for absence of gtklock. If you want, I can do it over the weekend.
