### ISSUE TITLE
`variables` file overwritten without backup at upgrade time

### ISSUE THREAD

**Issue by giraudan** [nwg-piotr/nwg-shell#142]
Whenever I upgrade `nwg-shell`, my `.config/sway/variables` file is overwritten with the default one withoug being backed up.

This isn't a huge issue because I only have 1 line that I modify, but it'd be nice to have my file backed up before the new one is written.

**Comment by nwg-piotr** [comment]
What do you mean by saying "Whenever I upgrade nwg-shell"? There happened 3 real upgrades that modified existing config files so far, only if it was really necessary. Just a version bumf does not overwrite anything.

**Comment by giraudan** [comment]
On many occasions, after upgrading (using my AUR helper), my `.config/sway/variables` file was overwritten.

I always modify it so that `nwg-drawer` doesn't stay in memory, doesn't display categories and doesn't display files.

On many occasions, after upgrading, I realized that `nwg-drawer` was longer to display, and showed me the categories and the files, and indeed, the modification I made to `.config/sway/variables` was no longer there.

Maybe my diagnostic is wrong, maybe it's not linked to the specific process of upgrading, but it sounds like a probable culprit.

Do you have any idea what could be causing this file to be overwritten by the default one?

**Comment by nwg-piotr** [comment]
If you modify the `variables` file manually, it's being overwritten every time you press the "Apply" button in nwg-shell-config. We don't parse the file back to the config utility, but we keep all the data in JSON format elsewhere. You should change settings in the shell config utility, to make them permanent.

Also, the settings you're talking about there are in the `autostart` file, not in `variables`.

**Comment by giraudan** [comment]
That makes sense, thanks a lot!
