### ISSUE TITLE
Setting up primary monitor

### ISSUE THREAD

**Issue by elevenhsoft** [nwg-piotr/nwg-shell#171]
Hi

I could not found a way to set up a primary monitor. I have a setup with dual monitor, DP-1 left and DP-2 right. I wish to have DP-2 as my primary to display nwg-panel etc. I was able to set workspace 1 for my DP-2 however, panels and the rest stays on DP-1 as a primary monitor. Is there any way to change this?

**Comment by nwg-piotr** [comment]
You didn't mention if you mean sway or Hyprland, however, I don't know of a way to set the primary output on Wayland. You may assign workspaces to outputs / monitors in nwg-displays. To assign a panel to an output, just use panel settings:

![image](https://github.com/nwg-piotr/nwg-shell/assets/20579136/3735cd43-8342-416b-ad08-445d02a192e4)

**Comment by elevenhsoft** [comment]
Oh well. I meant sway of course. Anyway, your solution is totally fine. It would solve my issue. However I did swap my cable so my DP-2 is now a DP-1 which solved the issue too. Thanks Piotr, your project is awesome :) I love it and it bring fun from using arch for me again :)

**Comment by nwg-piotr** [comment]
Thank you for the kind words. :)
