### ISSUE TITLE
Ubuntu Installation Details?

### ISSUE THREAD

**Issue by ShawnMcCool** [nwg-piotr/nwg-shell#184]
Hi there, I'm currently forced to choose between Ubuntu and OSX for a work laptop. I'm interested in NWG-SHELL, is it compatible with Ubuntu?

**Comment by nwg-piotr** [comment]
Hi. There's no common installer for my stuff on Ubuntu. I'm also unaware of any packages. Probably you could install all the components one by one.

**Comment by vicb** [comment]
Thanks for your awesome project.

Ubuntu/Debian being quite popular, it would be great to have packages / detailed instructions on how to install ngw-shell!

**Comment by nwg-piotr** [comment]
Hi @vicb,

I only do packaging for Arch User Repository, sorry. I haven't seen Ubuntu for years.
