### ISSUE TITLE
Tray disappeared after reinstall

### ISSUE THREAD

**Issue by xi-pinmping** [nwg-piotr/nwg-shell#24]
Hope this is an easy fix, but after archlabs took down their packages for the nwg-suite I hesitated to redownload the AUR packages because "if it ain't broke don't fix it"

But after I installed nwg-shell and it made me switch to all the bin packages instead of the other set from the aur, I am now unable to see the icons of apps in my system tray. This includes my wifi, discord, telegram, qtpass, etc. anything that gets minimized on close and I am unsure what to do to bring it back. I have checked available settings but did not see anything addressing this. Additionally, in the tray settings for qtpass all options to minimize are now grayed out, and the behavior follows other apps. Instead of minimizing, they just quit. 

Image added below. Thanks!

EDIT: I also am now unable to copy and paste across applications.

![image](https://user-images.githubusercontent.com/84921777/189721323-636b6c27-5db7-440b-9578-1e5ce0f4c4c6.png)

**Comment by nwg-piotr** [comment]
Well, the binary packages are only for the stuff written in go, so do not affect nwg-panel.

I only installed nwg-shell over the pre-2022.08.21 ArchLabs iso twice, and it went well, but wasn't easy. Something might have gone wrong on your side.

> I am now unable to see the icons of apps in my system tray

This should've been pulled together with the nwg-shell package, but just in case: do you have the `libappindicator-gtk3` package installed?

> I also am now unable to copy and paste across applications.

As above. Is the `wl-clipboard` package installed?

**Comment by xi-pinmping** [comment]
I do have both of these packages installed. Also while I've been poking around I discovered there is a volume and brightness slider I apparently cannot normally see lol

**Comment by nwg-piotr** [comment]
Your issue may be difficult to investigate remotely, especially after the upgrade, which is actually unsupported, as well by natemaia, as myself. I installed nwg-shell on the new AL iso, and it worked well, but on the daily basis I only test it on the fresh Arch Linux installation, done with the `archinstall` script.

**Comment by xi-pinmping** [comment]
I am unsure what change would have even broken these features. I tested with a fresh download and install through nwg-shell and nwg-shell-installer and it didn't work either even after a reboot.

**Comment by nwg-piotr** [comment]
Maybe something ArchLabs-specific? Have you tried with just Arch, as described in Wiki?

**Comment by xi-pinmping** [comment]
I've tried all the steps on the wiki including reinstalling with baph instead of paru. I have not tried with just arch or a fresh install. I do not have the availability to fully reinstall my operating system probably for another two weeks to a month though unfortunately.

**Comment by nwg-piotr** [comment]
Could you show me your `~/.config/sway/autostart` file?

**Comment by xi-pinmping** [comment]
```
exec rm /tmp/nwg-shell-check-update.lock
exec wlsunset -l -0.20727 -L -78.5086 -t 4500 -T 6500 -g 0.7
exec swaync -s /home/user/.config/swaync/preset-0.css
exec nm-applet --indicator
exec_always nwg-autotiling -w 1 2 3 4 5 6 7 8
exec_always nwg-panel -c preset-0 -s preset-0.css
exec_always nwg-shell-check-updates
exec swayidle timeout 1200 nwg-lock timeout 1800 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' 
```

**Comment by xi-pinmping** [comment]
I just checked my logs and it's asking if I have python-dasbus installed. I do have it installed for some reason it just isn't working.

**Comment by xi-pinmping** [comment]
Issue resolved. It was simple and stupid as hoped lol. I installed dasbus with pip and it worked fine. It was previously an archlabs package, after installing the updated packages I swapped it for vanilla arch python-dasbus since the archlabs version was no longer in the aur. Thanks for the help and great software!

**Comment by nwg-piotr** [comment]
Never use pip on Arch. :D I'm glad we have it sorted out.

**Comment by xi-pinmping** [comment]
I've already had my fair share of problems this way but the arch repo python-dasbus package wasn't working for me by itself.
