### ISSUE TITLE
[Feature Request] Add a clipboard manager

### ISSUE THREAD

**Issue by kuba3351** [nwg-piotr/nwg-shell#247]
Hello

I think nwg-shell should have a clipboard manager.  This tool increases speed and productivity by collecting an history of the items copied to clipboard and enables to search and paste these items in any time. KDE Plasma have this tool by default. I know that I can install it manually, but I think it should be fine to have it by default like we have notification center. Nwg-shell can be integrated with an existing tool or we can have a one written for nwg-shell.

**Comment by aposteeltje-bwg** [comment]
You can install 'mako' ,
a wlroots based clipboard manager.

Snippet of code to put in your hyprland.conf:

exec-once = mako
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

You can then call/view clipboard history with 'wofi' (if installed) by keybinding like this:
bind = $mainMod, V, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy     # Call Clipboard-History and show using wofi

See example screenshot below:
![swappy-20240104_204422](https://github.com/nwg-piotr/nwg-shell/assets/155484093/16c82427-b350-4daf-9b64-94d0df23af68)

**Comment by nwg-piotr** [comment]
Looks like a good idea. I'll check what I can do about it.

**Comment by aposteeltje-bwg** [comment]
I've tested the above, and i noticed that if you have a open floating window, and you call clip history.,
it also switches the floating window into tiling mode.

Don't know if that's wanted behaviour., and i can't seem to find out why it's doing that.

**Comment by nwg-piotr** [comment]
> I've tested the above, and i noticed that if you have a open floating window, and you call clip history.,
it also switches the floating window into tiling mode.

We won't use wofi/rofi/dmenu. We'll open our own centered window with a menu on gtk-layer-shell.

**Comment by nwg-piotr** [comment]
First working version:

![image](https://github.com/nwg-piotr/nwg-shell/assets/20579136/fbd4bcd2-9f18-447a-b907-bd18fe834a75)

**Comment by nwg-piotr** [comment]
Done: https://github.com/nwg-piotr/nwg-clipman
