### ISSUE TITLE
0.5.25 makes xwayland font rendering ugly with fractional scaling

### ISSUE THREAD

**Issue by nergdron** [nwg-piotr/nwg-shell#248]
previous to yesterday's 0.5.25 release, the font rendering in all my X apps looked great with hyprland+nwg-shell. per Arch wiki recommendations, I have the following env vars set to help with that:

```
GDK_SCALE=2
XDG_CURRENT_DESKTOP=Unity
```

however, after the release and a reboot, they all look terrible. it's worth noting that this is a likely the age old complication of using Wayland fractional scaling (primary monitor is 1.5), but it was working before, and now it's that terrible bad fractional scaling we used to have.

if there's new recommended environment var or wayland settings that fix this, I'm happy to get a pointer to those docs, but it also could be a legit bug.

![swappy-20240104_231624](https://github.com/nwg-piotr/nwg-shell/assets/292681/e99494b5-5e8a-40c8-9857-6a11918e1da0)

example shell script above in blackbox terminal, which should be wayland native since it's gtk4, but is also exhibiting the same issues. many wayland native apps (like firefox) are fine. :woman_shrugging:

**Comment by nwg-piotr** [comment]
This update only changed default values for the screen locker on hyprland. Nothing else has been changed.

**Comment by nergdron** [comment]
damn. must be something else in wayland or hyprland that changed then. unfortunate.

**Comment by nwg-piotr** [comment]
Maybe something wrong with Hyprland v0.34.0 on your machine? Looks well on my side.

**Comment by nwg-piotr** [comment]
Also Visual Studio Code looks good. I use IntelliJ stuff in real life, but nothing changed here as well.

![image](https://github.com/nwg-piotr/nwg-shell/assets/20579136/dfd3a9c7-baf9-4f06-8052-b56d64b7577b)

**Comment by nergdron** [comment]
vscodium on here looks fine too, either in X or Wayland mode. it seems to be mostly with electron apps (and blackbox), not even all xwayland apps. so it's pretty confusing. oh well! I'll try to figure it out, I'm just not sure where in the stack it'd be, given the weird combo of apps that're having problems.

**Comment by nwg-piotr** [comment]
Let me know in case you found something worth of mention in docs.

**Comment by nergdron** [comment]
will do!

**Comment by nwg-piotr** [comment]
> using Wayland fractional scaling (primary monitor is 1.5)

I've just tried 1.5 scale on my 2K monitor, and it Hyprland 0.34 refused to apply it:

![image](https://github.com/nwg-piotr/nwg-shell/assets/20579136/fb751b9b-37fe-4039-bc63-0983898df692)

Same happens if you try 1.4: it suggests 1.333333.

**Comment by nergdron** [comment]
that's so weird. it's not complaining here, but it does feel like hyprland changed its behaviour and is doing something weird now.

**Comment by nwg-piotr** [comment]
Vaxry keeps doing weird things all the time. ;)

**Comment by nwg-piotr** [comment]
https://www.reddit.com/r/hyprland/s/DDn2COWGTH
