### ISSUE TITLE
Length of nwg-panel exceeds display width in setup with multiple displays

### ISSUE THREAD

**Issue by 31PNMR** [nwg-piotr/nwg-shell#25]
I just freshly installed nwg-shell on arch. I've noticed that when using a setup with multiple displays with different resolutions, the width of the panel is not correct. In this example, I have a laptop with a 2256x1504 display, and two external monitors at 1920x1200.

Example of the panel being cut off on the 1920x1080.
![swappy-20220915_131600](https://user-images.githubusercontent.com/69053409/190496245-e8f3dbfe-2129-46df-8b89-85c5ea62d094.png)

It displays correctly on the laptop display.
![swappy-20220915_131629](https://user-images.githubusercontent.com/69053409/190496650-e7da55be-e52b-429b-a206-1e5eb874f928.png)

In the panel settings, I'm using `preset-0` with just some of the modules moved around. I changed the colors by editing the `preset-0.css`.

The panel was working normally before the update to nwg-shell. Thanks for any ideas.

**Comment by nwg-piotr** [comment]
Closing due to no further feedback.
