### ISSUE TITLE
[arch] Broken dependency on wlsunset

### ISSUE THREAD

**Issue by zette** [nwg-piotr/nwg-shell#258]
The wlsunset package on AUR is currently broken. As this package is hard dependency for both nwg-shell and nwg-shell-config packages it's blocking install of nwg-shell via arch.sh script.

**Comment by nwg-piotr** [comment]
Bad news, as we can't make it optional. Let's wait for sr.ht to be back on, or PKGBUILD is edited, as I see no simple solution at the moment. Thanks for reporting.

In case you need a fresh install, you may use [nwg-iso](https://github.com/nwg-piotr/nwg-iso) in the meantime. The wlsunset package comes in a local repo there.

**Comment by nwg-piotr** [comment]
The source seems to be back online.

**Comment by zette** [comment]
It worked, and I've managed to install. But meanwhile...

@nwg-piotr Plot twist: wlsunset has been removed from AUR, only wlsunset-git remains.

**Comment by nwg-piotr** [comment]
wlsunset just appeared in Arch Extra, should install from there.
