### ISSUE TITLE
GTK Icons for nwg-panel

### ISSUE THREAD

**Issue by 31PNMR** [nwg-piotr/nwg-shell#26]
I would like to use the GTK icons for nwg-panel. I selected them from the drop down list in panel settings. As you can see, the icons for notifications and brightness are replaced with the X icon. Is there a way to correct this? I tried looking through some of the config files, but wasn't able to find anything that specified which icon is used. In the GTK Settings, I did change the icon set to Yaru-blue which comes from the AUR package. Thanks for any assistance.

![swappy-20220915_131629](https://user-images.githubusercontent.com/69053409/190498277-412ca591-b9c1-47a1-922c-ce807c796676.png)

**Comment by nwg-piotr** [comment]
Well, you could select another icon for the help button:

![image](https://user-images.githubusercontent.com/20579136/190524701-b72ee463-47ea-4a45-8259-ad4d53bc00d5.png)

...and I could change the notification icon on my side, but most of brightness icons will be still missing from many GTK icon themes. That's why I provide monochrome light and dark icons: to use them if your icon theme is incomplete. Or you may use another icon theme.

**Comment by 31PNMR** [comment]
Thank you for the reply.

I'm looking in the settings, and I'm not sure how I can assign a different icon to the button in `nwg-panel-config`.

**Comment by nwg-piotr** [comment]
Try the Icon Picker button:

![image](https://user-images.githubusercontent.com/20579136/192058484-6b402422-32d5-4ba6-9060-532664d4ac52.png)

It will launch the helper window.

![image](https://user-images.githubusercontent.com/20579136/192058519-db067e4b-c771-4e25-a7e0-79316cfb21a4.png)

**Comment by 31PNMR** [comment]
Yes, I did see that. However, the icons I need to replace are for the notifications and brightness. I guess I'm missing something on how this works. Do I just put `notification` and `brightness` in the field where `launcher` is in your screenshots?

**Comment by nwg-piotr** [comment]
Those are not buttons. You can not change their icons.

**Comment by 31PNMR** [comment]
Okay, I expected there to be some config file somewhere which specified which graphic file is used, and then I could simply assign it that way. If there isn't, then this issue can be closed.

**Comment by nwg-piotr** [comment]
You wouldn't find all the necessary brightness icons in most GTK icon themes. In the panel that contains the Controls module, you must either use GTK icons based on Papirus, or custom light or dark icons.
