### ISSUE TITLE
accurate mouse position

### ISSUE THREAD

**Issue by aposteeltje-bwg** [nwg-piotr/nwg-shell#261]
Don't know if it's a GTK/QT issue,
but it envolves on several programs, eg. smplayer, vlc, google-chrome, 
pretty much any program, installed manually, independent of nwg-shell.

for example, 
if for example i'm on a browser, and i click on it's preferences.,
it's preferences appeares in the center of the screen, but the mouse cursor ofcourse stays where i left it:
on the top-right corner of the browser.

Now, when i try to choose a option with the mouse,
it does nothing....

I have to stay the mouse where i left it, on the top-right corner, and move down.
That  way, or with the keyboard, i can select it's options.

I can not point the mouse directly to the options

I do not have a screenrecorder yet, to show what i mean.

**Comment by aposteeltje-bwg** [comment]
since begin '90's i'm on Xorg,
so don't know much about wayland.
It's just a new adventure i'm diving in., but i'm a very fast learner....
wl-screenrec does nothing,
and simplescreenrecorder(despite it's warnings about wayland) gives only a blank screen with a mouse....
Could you please point me to a working screenrecorder for wlroots/wayland ?

**Comment by nwg-piotr** [comment]
> Could you please point me to a working screenrecorder for wlroots/wayland ?

wf-recorder works well for me.

All the troubles you described make me suppose you must be on Nvidia? Am I wrong?

**Comment by aposteeltje-bwg** [comment]
Nouveau.
Propr. Nvidia drivers were never installed.

lspci -nnk | grep -i vga -A2                                                                                                                                                                                                            04:00.0 VGA compatible controller [0300]: NVIDIA Corporation GK208B [GeForce GT 730] [10de:1287] (rev a1)
	Subsystem: Micro-Star International Co., Ltd. [MSI] GK208B [GeForce GT 730] [1462:8a9f]
	Kernel driver in use: nouveau

**Comment by aposteeltje-bwg** [comment]
https://github.com/nwg-piotr/nwg-shell/assets/155484093/7f7cb48a-c551-491b-8da6-8b3ac8683148

This one evolves VLC media player, but i have the same issue on several other programs....

**Comment by aposteeltje-bwg** [comment]
Ah. corrupt.
oh well...
Going to bed now, and trying to show later.
Good night.

**Comment by aposteeltje-bwg** [comment]
https://github.com/nwg-piotr/nwg-shell/assets/155484093/c0559632-db22-4798-abab-a7e3f622d2c8

This one evolves VLC media player, but i have the same issue on several other programs....
Very, very annoying.....

**Comment by aposteeltje-bwg** [comment]
Firefox is behaving neat, and shows wanted behaviour.
Google-chrome, however, is badly misbehaving, and shows the same issues as shown in the above example with VLC

**Comment by aposteeltje-bwg** [comment]
Google-chrome:

Uploading WhatsApp Video 2024-01-17 at 03.50.29.mp4…

**Comment by aposteeltje-bwg** [comment]
https://github.com/nwg-piotr/nwg-shell/assets/155484093/58262d4b-31fd-449a-8b68-b97f98d8dceb

Google-chrome, where i can't actually select something., unless i make a huge effort.

**Comment by nwg-piotr** [comment]
Well, I use Hyprland just on a single nvidia-powered machine (at the office), and it behaves decently here. The only issue is the mouse pointer that happens to disappear occasionally, but it reappears after few seconds. Nvidia is officially unsupported on both sway and Hyprland, and it has nothing to do with nwg-shell. Some hints on how to make it usable you may find here: https://wiki.hyprland.org/Nvidia
