### ISSUE TITLE
[feature req] post some sort of crowdfunding for all your hard work!

### ISSUE THREAD

**Issue by nergdron** [nwg-piotr/nwg-shell#290]
I was thinking today how much happier I am with my desktop experience since switching to nwg-shell on top of hyprland, and how great you've been about support. so why don't you have a liberapay or something, and myself and others can kick you a little money every month for all your much appreciated effort. link it on the nwg-shell page and in the repo, too! :grin:

**Comment by nwg-piotr** [comment]
Hi,

You're right, hardly anyone wants to use GitHub Sponsors. I was thinking about opening a Buy Me a Coffee account or something like that, but was always too lazy to do a proper research. Liberapay, you say... I need to take a closer look.

**Comment by nwg-piotr** [comment]
Liberapay looks good, indeed.

**Comment by nergdron** [comment]
yeah, I know a number of people/project who fund through there, and it's been relatively painless for me to setup recurring donations through them as well. seems like a good fit for this kinda project.

**Comment by nwg-piotr** [comment]
Haha, thank you! I needed someone to make me do it at last.

**Comment by nwg-piotr** [comment]
Well, I'll close as

**Comment by nwg-piotr** [comment]
Thanks again! :heart:
