### ISSUE TITLE
Installer script does not write correct path in hyprland.conf if XDG_CONFIG_HOME is set

### ISSUE THREAD

**Issue by ethereal-engineer** [nwg-piotr/nwg-shell#292]
I am taking steps to migrate my nwg-shell, hyprland, etc, dotfiles into my existing git-revisioned dotfiles hierarchy. This I found by doing a test run using:

`export XDG_CONFIG_HOME=<path>; nwg-shell-installer -a -hypr`

The paths written in the hyprland config file seem to be hardcoded to ~/.config...

**Comment by nwg-piotr** [comment]
If I remember well, we always use the `config_home` variable.

https://github.com/nwg-piotr/nwg-shell/blob/552f215da0a0451cf3671fade85725aa06eb6ffc/nwg_shell/installer.py#L31

**Comment by ethereal-engineer** [comment]
Ah. That would be why then.
