### ISSUE TITLE
gotk3 warnings and fail to build during make get

### ISSUE THREAD

**Issue by dpgraham4401** [nwg-piotr/nwg-shell#3]
During the installation process for all nwg-shell packages written in Go, trying from AUR and manually, the make get command fails with the attached warnings to stdout.

I guess this is more of a heads-up since It apperars that's in internal [gotk3 issue](https://github.com/gotk3/gotk3/issues/837). 

[make_get_output.txt](https://github.com/nwg-piotr/nwg-shell/files/7966824/make_get_output.txt)

**Comment by nwg-piotr** [comment]
These warning have always been here, and yes, they come from gotk3. Did you have any issues with building?

**Comment by dpgraham4401** [comment]
I couldn't install them from AUR. Sorry, just tried again manually and yes that works. Sorry brain fart.

**Comment by nwg-piotr** [comment]
gotk3 has its oddities, and also does not implement all the gtk3 stuff, but everything is better to me than coding in C/C++. ;)
