### ISSUE TITLE
panel displays error output if baph is not installed.

### ISSUE THREAD

**Issue by naund** [nwg-piotr/nwg-shell#30]
Hallo,
thank you for this tool.  I have just one small issue:

The documentation recommending to use baph, but doesn't insist in it. Iif baph isn't installed the sway-update script is throwing an error with is displayed in the panel.  This output is displayed in the panel. Could you make this script more robust, to cover installations without installed baph (I'm using paru BTW;).

**Comment by nwg-piotr** [comment]
This is just an executor, even if pre-installed. Fell free to delete it or use another script.

![image](https://user-images.githubusercontent.com/20579136/199101658-320920cc-47e2-49ae-86f8-057e9dfec1f5.png)
