### ISSUE TITLE
suggestion: use also weblate for translations

### ISSUE THREAD

**Issue by zen0bit** [nwg-piotr/nwg-shell#310]
Can make things easier for translators and better tracking of translations..

**Comment by nwg-piotr** [comment]
Well, we already have a translation tool, and nobody complained about it being too hard to use - because hardly anyone wanted to contribute so far. I won't spend months to implement another translation system to all the nwg-shell components just to gain a couple of new translations.

**Comment by zen0bit** [comment]
> Well, we already have a translation tool, and nobody complained about it being too hard to use - because hardly anyone wanted to contribute so far. I won't spend months to implement another translation system to all the nwg-shell components just to gain a couple of new translations.

No need to implement anything.
just put completed traslations json file on weblate

Just start translating nwg (used to weblate)

But your implementation is also nice. Just taked me while before I find full json files in repo

**Comment by nwg-piotr** [comment]
I'll take another look later tonight.

**Comment by nwg-piotr** [comment]
I have no web server for self-hosted weblate, nor do I want to pay € 17 a month.

**Comment by zen0bit** [comment]
You don't have to pay as open source software developer with public project. But you must apply for that option.. take some time

But I am sure you will get there for free 😉

**Comment by zen0bit** [comment]
@nwg-piotr sorry for continuing
Did you tried apply for free hosting on weblate?

### Weblate proudly supports libre projects

If you feel that being supported by Weblate will help your libre project, [set it up](https://hosted.weblate.org/hosting/) and get the Libre plan gratis. It has the same limits as the 160k plan, and is only for public projects.

**Comment by nwg-piotr** [comment]
I'd need a 6-pack to read a 33 kB long terms of use. ;)
