### ISSUE TITLE
config got overwriten

### ISSUE THREAD

**Issue by KCkingcollin** [nwg-piotr/nwg-shell#317]
i recognize i am partially at fault for not having a backup, but why does the arch installation script not make a backup of your current hyprland config? i am now forced to spend hours looking up all the keywords and commands i used in my original config. please at very least add a warning in the wiki for the users of the arch script that their configs will be overwritten

**Comment by nwg-piotr** [comment]
The installation steps described in Wiki concern fresh installed systems. I see no point in backing up default configs.

**Comment by KCkingcollin** [comment]
i understand that in hindsight, but why cant there at least be instructions on installation for a already configured system in the wiki? also is it not common for people to carry their home partition over? just a warning in the wiki would be enough, i just don't what anyone else to have to go through what im doing rn

**Comment by nwg-piotr** [comment]
This Wiki page is open for public edition. Feel free to add the warning.

**Comment by KCkingcollin** [comment]
ah, in that case i can give it a shot, let me finish up my config, and ill write up something for it rq, i did see the edit button, but wasn't sure if i was welcome lol

**Comment by nwg-piotr** [comment]
It was necessary, as I couldn't keep up with packagers. ;)

**Comment by KCkingcollin** [comment]
well then, ill go ahead and close the issue then, and ill add some wiki additions once im done re-configuring like i said
