### ISSUE TITLE
Upgrading to python 3.12 breaks nwg-shell

### ISSUE THREAD

**Issue by jamesredwards** [nwg-piotr/nwg-shell#327]
Using Arch and pacman -Syu to update. nwg-shell installed with AUR helper. When the /usr/lib/python3.11 directory changes to /usr/lib/python3.12 it breaks nwg-shell-config. I have no other versions of python installed on my machine, just the system one (3.11.8)

**Comment by nwg-piotr** [comment]
Just reinstall nwg-shell-config. I triggered this by changing the revision name to 0.5.36-2, but can not do it forever, until everyone on Earth upgrades to python3.12. Same applies to all AUR python-based packages.

**Comment by jamesredwards** [comment]
thanks
