### ISSUE TITLE
Enhancement: CPU power settings for laptops

### ISSUE THREAD

**Issue by legop3** [nwg-piotr/nwg-shell#364]
Hello, I think that it would be nice to have settings built into the taskbar style panel for CPU power modes or frequency settings. Could utilize cpupower package which already exists. Maybe look at cpupower-gui. just a suggestion.

**Comment by nwg-piotr** [comment]
I took a quick look. It seems to have much too many feature as for a simple panel module. Also some features seem not to work on my CPU (AMD).
