### ISSUE TITLE
aur package problems

### ISSUE THREAD

**Issue by killertofus** [nwg-piotr/nwg-shell#373]
the [aur package](https://aur.archlinux.org/packages/nwg-shell) should not have dependencies to hyprland/sway packages when this package works with other wayland based compositors ie dwl those should be optional alongside personal preferences ie having foot as a term when any term works. Below is a updated pkgbuild that reflects those changes

https://mystb.in/1fbe88e6b85a654eb4

**Comment by nwg-piotr** [comment]
This package goes to Arch/Extra soon. Dunno what the PKGBUILD is going to look like after that.
