### ISSUE TITLE
Possible fix for using ; or && in exec.

### ISSUE THREAD

**Issue by Jankatay** [nwg-piotr/nwg-shell#397]
### Problem:
Problems when "exec" has to do more than one command.

### Example:
Intend: Wait for nwg-bar to hide and after lock the screen with [swaylock-effects](https://github.com/mortie/swaylock-effects)
Result: Nothing happens
` "exec": "sleep 1; swaylock --screenshots --effect-vignette 0:1 --effect-blur 3x3 --indicator-x-position -500",`

### Possible solution:
Modify tools.go by replacing line 195:
 ```
 -195: cmd := exec.Command(elements[cmdIdx], elements[1+cmdIdx:]...)  
+195: cmd := exec.Command("sh", "-c", command)  
```
### Sidenote:
If I made any grammar mistakes sorry for my bad english. 
I have only tested on arch+sway.

**Comment by Jankatay** [comment]
Wrong repo. Sorry about that.

**Comment by nwg-piotr** [comment]
This should be done by `swaymasg exec`, see https://github.com/nwg-piotr/nwg-menu/blob/5583a5589c64ff74c0512fc6b66f0f0a0ff390af/tools.go#L587. Nwg-bar has been a bit out of date since I stopped using it in nwg-shell. Need to back-port some most essential changes from nwg-drawer/nwg-menu one day.
