### ISSUE TITLE
minor bug: duplicate folder suggestions during installation

### ISSUE THREAD

**Issue by matthis-k** [nwg-piotr/nwg-shell#4]
The `~/.local/bin` directory is suggested multiple times during installation with `nwg-shell-installer`:
![image](https://user-images.githubusercontent.com/69082876/155884482-3f67846e-2f86-4a15-b38a-3af3d98f0611.png)

**Comment by nwg-piotr** [comment]
Could you show me your `$PATH`?

**Comment by matthis-k** [comment]
Here it is:
`/usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /home/matthisk/.local/bin /home/matthisk/.local/bin`
Duplicate is in here, seems to be the reason

**Comment by nwg-piotr** [comment]
Yes, thanks. I'll add a line to skip already added paths, however.
