### ISSUE TITLE
Unable to remove launcher hotkey, no GUI option found.

### ISSUE THREAD

**Issue by hecto600** [nwg-piotr/nwg-shell#402]
I'm trying to remove the alternative application drawer hotkey SUPER key located in includes.conf with the line `bindr = SUPER, SUPER_L, exec, $launcher`. I couldn't find any option in nwg-shell. Manually removing the bind  in includes.conf would  recreate it after reboot. Although I could change other bindings manually through hyper.conf. 
System info: Arch linux, hyperland 0.43.

**Comment by nwg-piotr** [comment]
It's here:

![obraz](https://github.com/user-attachments/assets/99297739-7567-44f4-b444-340485579ea1)
