### ISSUE TITLE
nwg-shell, Fedora, Waydroid - clipping window edge

### ISSUE THREAD

**Issue by mattdrepo** [nwg-piotr/nwg-shell#409]
Sorry about the poor descriptor for the issue I am having.

But to summarise.  Installing Fedora Sway Beta Spin, upgrading to rawhide and then running the script here to install the nwg-shell, leaves me with a clipped Waydroid window, whereby the bottom panel/pane intersects with my waydroid session leaving the buttons for androd hidden.

Could I autohide the panels?  Or has someone a solution for the application in question?  Namely, like your decorations for apps you have integrated into the shell design, a method for fitting waydroid in?

**Comment by nwg-piotr** [comment]
There's no auto-hide option. You can only show/hide on signal, 64 by default. I use it with the Super+F3 key.

```
bind = $mainMod, F3, exec, pkill -f -64 nwg-panel
```

![obraz](https://github.com/user-attachments/assets/a05329f7-16f0-48fd-8ccd-b95297d768e5)
