### ISSUE TITLE
Not installing skel for 'nwg-displays'

### ISSUE THREAD

**Issue by mac-a-r0ni** [nwg-piotr/nwg-shell#437]
I've tried the last 6 releases and none of them install a config skel for nwg-displays, yet when running 'nwg-shell-installer -a' I'm given an error that it cannot find the nwg-displays skel file during initialization.

Has this been dropped from the default config?

**Comment by nwg-piotr** [comment]
It seems that the source folder is missing. I haven't noticed it so far, as the program creates it on first run. Will fix tonight.

**Comment by nwg-piotr** [comment]
It was in place, but I haven't listed it in setup.py -> package_data{}. Should be well now.
