### ISSUE TITLE
[Feature request] Adjust default save location screenshots

### ISSUE THREAD

**Issue by thesaigoneer** [nwg-piotr/nwg-shell#453]
**Is your feature request related to a problem? Please describe.**
When using the integrated screenshot utility screenshots are now saved in /home/'user'/Screenshots

**Describe the solution you'd like**
Instead of creating a new folder in the user's home directory I'd think it would be better to save in /home/'user'/Pictures/screenshots

**Additional context**
See the attached scrot for the current setup
![image](https://github.com/user-attachments/assets/2f5c6895-4889-4891-889a-a88c3e9b8692)

**Comment by nwg-piotr** [comment]
OK, the target dir is now defined like this:

```bash
PICTURES=$(xdg-user-dir PICTURES)
DIR=${SCREENSHOT_DIR:=$PICTURES/Screenshots}
```

You can still use your own path by defining the `SCREENSHOT_DIR` environment variable.

**Comment by nwg-piotr** [comment]
I'll release when nwg-shell-congig 0.5.53 hits the [Extra] repo. Need an icon added to that package. :D

**Comment by thesaigoneer** [comment]
Okay mate, I'll be installing nwg-iso later this week and the update after that will probably catch it. Thanks!

**Comment by nwg-piotr** [comment]
Done.

**Comment by thesaigoneer** [comment]
Great man, thanks a lot!
