### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sgse** [nwg-piotr/nwg-shell#5]
<img width="252" alt="image" src="https://user-images.githubusercontent.com/17575778/162177495-b8a99b35-7543-4f6e-b6d3-84fabb986571.png">

https://github.com/nwg-piotr/nwg-shell/tree/master/resources

**Comment by nwg-piotr** [comment]
Very true. Fixed, thank you!

**Comment by sgse** [comment]
I have to thank :-)

**Comment by nwg-piotr** [comment]
I lost the server with all my GitHub pictures the other day, and had to make them all from scratch, and host somewhere. This caused the mess which still shows up in unexpected places. ;)
