### ISSUE TITLE
libegl error when running sway after installation

### ISSUE THREAD

**Issue by manan-gup** [nwg-piotr/nwg-shell#50]
Hi, I wanted try nwg-shell and I was trying to install it on a fresh ArchLinux VM in Gnome Boxes flatpak. When I ran `sway` after following the installation instructions I got the following error:

![Screenshot from 2023-01-05 08-20-12](https://user-images.githubusercontent.com/77879361/210691153-19ac1ebb-21e1-46c9-8650-e6b7a836acdf.png)

If there's any way to fix or troubleshoot this then please let me know.

P.S. I have an Intel i3 with integrated graphics and I chose the Intel driver option in `archinstall`.

**Comment by manan-gup** [comment]
Ok, I'll see if I can try it on VirtualBox. Thanks!

**Comment by nwg-piotr** [comment]
> Ok, I'll see if I can try it on VirtualBox. Thanks!

Ber aware, that you'll need to set `WLR_NO_HARDWARE_CURSORS=1`, and live with no hardware cursor. :/
