### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by Henry-Hiles** [nwg-piotr/nwg-shell#72]
Hello there! This looks super cool and I would love to try it. If a NixOS flake could be made for this project then that would be amazing! Thanks.

**Comment by nwg-piotr** [comment]
Hi,

I'd love to be of help, but unfortunately I know nothing on NixOS. Maybe one day I'll find some time to give it a try, but packaging should be done by advanced users. Most of the packages are already in nixpkgs, so it shouldn't take much time.

For now I maintain the Arch Linux version, @kuba3351 has just finished packaging for Fedora, and @mac-a-r0ni is about to have Slackware packages ready. If you manage to find a NixOS packager, feel free to open a thread in https://github.com/nwg-piotr/nwg-shell/discussions/categories/porting-for-other-distros.
