### ISSUE TITLE
Two broken links on the project's landing page

### ISSUE THREAD

**Issue by microHertz** [nwg-piotr/nwg-shell#75]
I noticed a couple broken links in the [credits](https://nwg-piotr.github.io/nwg-shell#credits) section on the project's landing page. 

go-singleinstance link gives a 404. It should point to: https://github.com/allan-simon/go-singleinstance

wlr-randr link goes to nwg-shell project page. It should point to: https://sr.ht/~emersion/wlr-randr/

**Comment by nwg-piotr** [comment]
Fixed, thank you.
