### ISSUE TITLE
Trouble Waking From Sleep

### ISSUE THREAD

**Issue by jlsiemering** [nwg-piotr/nwg-shell#8]
After closing the lid to put the system in sleep, it doesn't properly wake, just a black screen with no option to unlock. I'm able to open another tty and start sway from there, though. I'm on a fresh install of Arch and followed the installation instructions. Any suggestions or advice is appreciated!

If there are any logs or details I can provide that may help, let me know!

**Comment by nwg-piotr** [comment]
Well, it doesn't have much to do with the shell itself. We use lines from the standard sway config:

```
### Turn off screen on lid closed
set $laptop eDP-1
bindswitch lid:on output $laptop disable
bindswitch lid:off output $laptop enable
```

It does not make the laptop sleep, just disables/enables the output named `eDP-1`. If you have an external display, you may open terminal on it and try:

`swaymsg output eDP-1 disable` / `swaymsg output eDP-1 enable`

and see what's happening.
