### ISSUE TITLE
Lock screen before sleep

### ISSUE THREAD

**Issue by felixg3** [nwg-piotr/nwg-shell#86]
Dear Piotr,

Foremost, thank you for creating a wonderful out-of-the-box experience for Sway. I am using it since yesterday and I am positively surprised.

However, when I close the lid of my laptop and wake up the device from sleep, the screen is not locked. If I fill the "before sleep" field with nwg-lock, I do receive a black screen when waking up the device from sleep.

Any suggestions to proceed?
Thank you!

**Comment by nwg-piotr** [comment]
I'm glad that you sorted it out.
